# url: "http://clementrenaud.com/slides"
# permalink: /:path
# baseurl: ""
# relative_permalinks: false

exclude:
  - bin
  - oldies

sass:
    sass_dir: scss

description: "Clément Renaud's presentations."

keywords: "data, visualisation, design, research, China, generative design, network analysis, makers, Shenzhen, topogram, Rhône-Alpes, Lyon, memes, digital writings"

author:
  name: "Clément Renaud"
  tagline: "Algorithmic writings"
  headline: "Data rows & newspapers columns"
  email: "hi@clementrenaud.com"

collections:
    talks:
        output: true
